### ISSUE TITLE
eModePointer

### ISSUE THREAD

**Issue by rofl0r** [ivan-mogilko/ags-lastfurious#2]
in GlobalScript.asc:  Mouse.Mode = eModePointer;

i can't find this symbol declared anywhere in ags sources, there's only a reference in Manual.tex (which uses it as a function arg name). what's wrong here ?

**Comment by ivan-mogilko** [comment]
There's a number of symbols that AGS generates and adds to builtin script header. These include script names of objects such as Cursors, Fonts, Characters and so on.

**Comment by ivan-mogilko** [comment]
I guess this question is related to your experiments with standalone compiler?

Yes, this might be an issue. Editor, or any other tool able to parse game XML, should be outputting all additional headers as files before compilation.

**Comment by rofl0r** [comment]
> There's a number of symbols that AGS generates

ah. i figured something like this happens when encountering a similar undefined symbol in another .asc file.

> and adds to builtin script header before script compilation.

ah, thanks for clarification.

> I guess this question is related to your experiments with standalone compiler?

indeed.

> Editor, or any other tool able to parse game XML, should be outputting all additional headers as ash files before compilation.

yes, that would be helpful. maybe these ids should be saved in a dedicated header to begin with, rather than being saved in xml ?

**Comment by ivan-mogilko** [comment]
> yes, that would be helpful. maybe these ids should be saved in a dedicated header to begin with, rather than being saved in xml ?

XML stores game data, which is objects and fields that user may edit. Script header is a deriative from that; script constants are sometimes taken from the object names, and are not always identical (they may be generated with certain preffix, like in cursor's and font's case). Having to parse these from script header would unnecessarily complicate things.
